// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGqdCliibU_wEeUMikveIi42ymp2weWuM',
    appId: '1:468957971292:web:d4250371b42be46f1ef799',
    messagingSenderId: '468957971292',
    projectId: 'retailcheck-e12d2',
    authDomain: 'retailcheck-e12d2.firebaseapp.com',
    storageBucket: 'retailcheck-e12d2.firebasestorage.app',
    measurementId: 'G-XKG0LWP912',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBQEmLdKXt0P3AX9usT-oYNNe-czUHmRs',
    appId: '1:468957971292:android:c62dcb9d2fe94e521ef799',
    messagingSenderId: '468957971292',
    projectId: 'retailcheck-e12d2',
    storageBucket: 'retailcheck-e12d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA59ZSxQ1J36rEV7tRKKUwpM_PiEaohMGc',
    appId: '1:468957971292:ios:9de59645d4fa6cb81ef799',
    messagingSenderId: '468957971292',
    projectId: 'retailcheck-e12d2',
    storageBucket: 'retailcheck-e12d2.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA59ZSxQ1J36rEV7tRKKUwpM_PiEaohMGc',
    appId: '1:468957971292:ios:9de59645d4fa6cb81ef799',
    messagingSenderId: '468957971292',
    projectId: 'retailcheck-e12d2',
    storageBucket: 'retailcheck-e12d2.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGqdCliibU_wEeUMikveIi42ymp2weWuM',
    appId: '1:468957971292:web:b97bd8361a24b7b41ef799',
    messagingSenderId: '468957971292',
    projectId: 'retailcheck-e12d2',
    authDomain: 'retailcheck-e12d2.firebaseapp.com',
    storageBucket: 'retailcheck-e12d2.firebasestorage.app',
    measurementId: 'G-JJ7SKLCSE9',
  );

}